# Generated by GPT-5.2 on 2026-04-22

from django.contrib.auth import get_user_model
from django.db import migrations


def create_default_user(apps, schema_editor):
    User = get_user_model()
    username = "zx"
    password = "zknu@@42"

    if User.objects.filter(username=username).exists():
        return

    User.objects.create_user(username=username, password=password)


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_user, migrations.RunPython.noop),
    ]
