# Generated by Django 4.2.7 on 2026-04-22 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_create_default_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("listening", "听力"),
                            ("reading", "阅读"),
                            ("translation", "翻译"),
                            ("writing", "作文"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="专项",
                    ),
                ),
                (
                    "minutes",
                    models.PositiveIntegerField(verbose_name="训练时长（分钟）"),
                ),
                (
                    "session_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="训练日期",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "四级训练记录",
                "verbose_name_plural": "四级训练记录",
                "ordering": ["-session_date", "-created_time"],
            },
        ),
    ]
