# Generated by Django 4.2.30 on 2026-04-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_topic_timeentry"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="timeentry",
            new_name="tasks_timee_user_id_27a2e3_idx",
            old_name="tasks_timeentry_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="timeentry",
            new_name="tasks_timee_user_id_9e6320_idx",
            old_name="tasks_timeentry_user_topic_date_idx",
        ),
    ]
