# Generated by Django 4.2.30 on 2026-04-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="time_accounting_basis",
            field=models.CharField(
                choices=[
                    ("deadline", "按预定时间"),
                    ("completed_time", "按实际完成时间"),
                ],
                db_index=True,
                default="completed_time",
                max_length=20,
                verbose_name="计时口径",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="source_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="tasks.task",
                verbose_name="来源任务",
            ),
        ),
    ]
